export const IDEAS_DATA_REQUESTED = 'IDEAS_DATA_REQUESTED';
export const IDEAS_DATA_RECEIVED = 'IDEAS_DATA_RECEIVED';
export const IDEAS_DATA_NOT_RECEIVED = 'IDEAS_DATA_NOT_RECEIVED';

export const IDEA_ADD = 'IDEA_ADD';

export const IDEA_UPDATE = 'IDEA_UPDATE';

export const IDEA_DELETE = 'IDEA_DELETE';
